### PR TITLE
Restrcutred project and added Inventory and Item classes

### PR DESCRIPTION
**Pull request by NasserAlzughaibi93**
Please merge this before you work on it anymore.

### CODE REVIEW

**Comment by NasserAlzughaibi93** [comment]
Ignore the workspace.xml change that was a mistake those shouldn't be comitted.

Also don't commit the cmake-debug folders anymore those are supposed to be unique to each of us

**Comment by ausroa** [comment]
Will do. My bad. I will figure out the merge before working on it anymore. Did my changes screw anything up on your end?

**Comment by NasserAlzughaibi93** [comment]
Yeah the ,idea and debug folders messed it all up on my mac

**Comment by ausroa** [comment]
Ok. Do i need to change anything? Or do you want me to go ahead and just merge and deal with what happens?

**Pull request merged**
